services:
  gpt-cpu:
    image: ${REGISTRY_USER}/${REGISTRY_REPO}-gpt-cpu:${IMAGE_TAG}
    profiles: ["cpu"]
    environment:
      - NUM_THREADS=${NUM_THREADS}
      - BATCH_SIZE=${BATCH_SIZE}
      - MAX_PROMPT_LENGTH=${MAX_PROMPT_LENGTH}
      - MAX_TOKENS=${MAX_TOKENS}
      - GPU_LAYERS=${GPU_LAYERS}
      - MODEL_PATH=/app/models/deepseek-llm-7b-chat.Q4_K_M.gguf
      - USE_GPU=false
      - BATCH_SIZE=${BATCH_SIZE}
      - NUM_THREADS=${NUM_THREADS}
    volumes:
      - ./cache/models:/app/models
      - ./cache/cache:/root/.cache/llama_cpp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 60s

  mailer:
    image: ${REGISTRY_USER}/${REGISTRY_REPO}-mailer:${IMAGE_TAG}
    environment:
      - EMAIL_USER=${MAIL_USER}
      - EMAIL_PASS=${MAIL_PASS}
      - IMAP_SERVER=${MAIL_HOST}
      - ORCHESTRATOR_URL=http://orchestrator:5000/process_email

  db:
    image: ${REGISTRY_USER}/${REGISTRY_REPO}-db:${IMAGE_TAG}
    volumes:
      - ./cache/sqlite:/data

  orchestrator:
    image: ${REGISTRY_USER}/${REGISTRY_REPO}-orchestrator:${IMAGE_TAG}
    environment:
      - DB_PATH=/data/db.sqlite
      - GPT_URL=http://${GPT_SERVICE}:5000/gpt
      - BOT_EMAIL=${MAIL_USER}
      - BOT_PASS=${MAIL_PASS}
      - SMTP_SERVER=${MAIL_HOST}
    volumes:
      - ./cache/sqlite:/data
      - ./cache/vector_db:/app/vector_db
      - ./assets/:/app/assets

networks:
  default:
    name: gpt-network      