FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    python3 python3-pip python3-dev build-essential cmake git \
	curl \
  && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir --upgrade pip \
 && pip3 install llama-cpp-python

WORKDIR /app

COPY requirements.txt load_model.py entrypoint.sh ./

RUN pip3 install --no-cache-dir -r requirements.txt

RUN chmod +x entrypoint.sh

EXPOSE 5000

ENTRYPOINT ["./entrypoint.sh"]