FROM nvidia/cuda:12.4.0-runtime-ubuntu22.04

RUN apt-get update && apt-get install -y \
    python3 python3-pip \
	bash \
    && rm -rf /var/lib/apt/lists/*

# Instala directamente la wheel para CUDA 12.4
RUN pip3 install --no-cache-dir --upgrade pip && \
    pip3 install --no-cache-dir \
        llama-cpp-python \
        --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu124

WORKDIR /app
COPY requirements.txt load_model.py entrypoint.sh ./
RUN pip3 install --no-cache-dir -r requirements.txt
RUN chmod +x entrypoint.sh

EXPOSE 5000
ENTRYPOINT ["./entrypoint.sh"]